### PR TITLE
Fix: night value.

### PR DESCRIPTION
**Pull request by MrMohamedAbdallah**
Using night input value instead of the input DOMElement itself.

### CODE REVIEW

**Comment by MrMohamedAbdallah** [comment]
I'm sorry, But I can't go through all the code to detect the issue. I just saw the night error was an easy fix.

For more help, I suggest you to open a new discussion on Laracasts with more specific details. and close the old one if that solved.

**Comment by webdev866** [comment]
/hello MrMohamedAbdellah, the issue is still related to calculating total amount, not with nights. What I mean is if the total amount is calculated and you suddenly you changed the departure date, the number of nights is calculated correctly but the total amount doesn't change

**Comment by webdev866** [comment]
> const numberOfRooms = document.querySelector('#number_of_room').value || 0;

Hello,
It didn't work
error in console

Uncaught TypeError: can't access property "value", document.querySelector(...) is null
    calculateTotal http://la3.test/admin/create-vouchers/create:319

**Comment by gazz96** [comment]
put your js into head or before the element.

**Comment by webdev866** [comment]
put it at which line exactly?

**Comment by gazz96** [comment]
https://github.com/webdev866/vouchermanager/blob/main/resources/views/layouts/app.blade.php
try put your js script in <head> tag

**Comment by webdev866** [comment]
it didn't work, can you run my repo on your pc, I'm using laragon on Windows10.
Make sure to click right then select Quick App and select Blank App, Go to C:/laragon/www/your-app and issue the following commands:

cp .env.example .env  (I used Cmder) cmder.net
edit .env with database credentials
composer install
php artisan migrate --seed
php artisan key:generate
php artisan storage:link

browse to webpage
login admin@admin.com
pass: password

can you please try and let me know

**Comment by gazz96** [comment]
First change
`<input type="text" name="night" id="night" disabled>` to `<input type="text" name="night" id="night" readonly>`
and then change **calculateTotal** function  to this
```
                                const calculateTotal = function() {
                                    const roomPrice = room_price.value || 0;
                                    const numberOfRooms = number_of_room.value || 0;
                                    const night = document.getElementById("night").value || 0
                                    //const nights = calcNights() || 0;
                                    let total = 0;
                                    if (night) {
                                        total = (parseInt(roomPrice) * parseInt(numberOfRooms)) * parseInt(night);
                                        console.log(night, roomPrice, numberOfRooms)
                                    }
                                    total_amount.value = total.toFixed(2)
                                }
```

**Pull request closed without merging**
